name: Spellcheck Action
on: push
jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: rojopolis/spellcheck-github-actions@0.34.0
      name: Spellcheck
      with:
        config_path: spellcheck_config.yml # put path to configuration file here
        source_files: test/1.md test/Debugging.md test/Overview.md
        task_name: Markdown