name: spellcheck_2
on: push
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    name: Spellcheck
    steps:
      - uses: actions/checkout@v4
      - uses: tbroadley/spellchecker-cli-action@v1
        with:
          files: "markdown_files/Debugging.md markdown_files/Overview.md"
          quiet: true
